# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
ripser_cpp_dist <- function(dataset, dim, thresh, ratio, p) {
    .Call(`_ripserq_ripser_cpp_dist`, dataset, dim, thresh, ratio, p)
}

